apiVersion: v1
data:
  APP_NAME: platfrom_engineering
  ENV: dev
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-21T13:17:06Z"
  name: app-config
  namespace: pe-day2
  resourceVersion: "7480"
  uid: 71a28f3a-63ab-4053-a52e-bcda1e257eed
