apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"env-demo","namespace":"pe-day2"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"env-demo"}},"template":{"metadata":{"labels":{"app":"env-demo"}},"spec":{"containers":[{"env":[{"name":"APP_NAME","valueFrom":{"configMapKeyRef":{"key":"APP_NAME","name":"app-config"}}},{"name":"ENV","valueFrom":{"configMapKeyRef":{"key":"ENV","name":"app-config"}}},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"DB_USER","name":"app-secret"}}},{"name":"DB_PASS","valueFrom":{"secretKeyRef":{"key":"DB_PASS","name":"app-secret"}}}],"image":"nginx:latest","name":"app"}]}}}}
  creationTimestamp: "2026-01-21T13:13:14Z"
  generation: 1
  name: env-demo
  namespace: pe-day2
  resourceVersion: "7487"
  uid: 2210d3fc-51be-4b7b-869f-884925c16757
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: env-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: env-demo
    spec:
      containers:
      - env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME
              name: app-config
        - name: ENV
          valueFrom:
            configMapKeyRef:
              key: ENV
              name: app-config
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: app-secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: app-secret
        image: nginx:latest
        imagePullPolicy: Always
        name: app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-21T13:13:14Z"
    lastUpdateTime: "2026-01-21T13:13:19Z"
    message: ReplicaSet "env-demo-8664896bc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-01-21T13:17:10Z"
    lastUpdateTime: "2026-01-21T13:17:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
